### ISSUE TITLE
FYI: sketchy link in README

### ISSUE THREAD

**Issue by loiccoyle** [mohd-akram/base16-pygments#5]
Hi there, just to let you know that the link in the readme (http://chriskempson.com/projects/base16/) now points to a sketchy crypto gambling site. Its probably wise to change it to https://github.com/chriskempson/base16-schemes-source or https://github.com/tinted-theming/base16-schemes or even https://tinted-theming.github.io/base16-gallery/ .

**Comment by mohd-akram** [comment]
Thanks for letting me know, I'll fix this.
